sudo: required
script:
    - sudo apt-get update
    - sudo apt-get install build-essential
    - tar -xzvpf MakeAnOS.tar.bz2 MakeAnOS
    - cd MakeAnOS
    - cd tools
    - ls -la
    - chmod a+x *
    - ./nask
    - ./gas2nask
    - ./cc1
    - ls -la
    - cd ../src
    - pwd
    - make
